package com.afriland.ticket2cash.cashback.engine;

public enum CashbackDecisionCode {
    APPROVED,
    APPROVED_WITH_LIMIT,
    REJECTED_INVALID_AMOUNT,
    REJECTED_CAMPAIGN_NULL,
    REJECTED_CAMPAIGN_INACTIVE,
    REJECTED_CAMPAIGN_OUT_OF_PERIOD,
    REJECTED_NO_CASHBACK_RULE,
    REJECTED_MIN_AMOUNT_NOT_REACHED,
    REJECTED_FRAUD_SUSPECTED,
    REJECTED_DUPLICATE_TICKET,
    REJECTED_BUDGET_EXCEEDED,
    REJECTED_TRANSACTION_REF_REQUIRED,
    REJECTED_CARD_HASH_REQUIRED,
    REJECTED_MCC_NOT_ELIGIBLE,
    REJECTED_CHANNEL_NOT_ELIGIBLE,
    REJECTED_CARD_BIN_NOT_ELIGIBLE,
    REJECTED_DAILY_LIMIT_REACHED,
    REJECTED_MONTHLY_LIMIT_REACHED,
    REJECTED_CLIENT_CAP_REACHED
}
