package com.afriland.ticket2cash.rewards;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(Ordered.LOWEST_PRECEDENCE)
public class RewardLedgerSchemaMigration implements CommandLineRunner {
    private final JdbcTemplate jdbcTemplate;
    public RewardLedgerSchemaMigration(JdbcTemplate jdbcTemplate) { this.jdbcTemplate = jdbcTemplate; }

    @Override public void run(String... args) {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS reward_ledger_entries ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "source_type VARCHAR(50) NOT NULL, source_ref VARCHAR(160) NOT NULL, customer_ref VARCHAR(160),"
                + "masked_card VARCHAR(32), card_hash VARCHAR(255), merchant_id BIGINT, merchant_name VARCHAR(255), campaign_id BIGINT,"
                + "benefit_type VARCHAR(50) NOT NULL, cashback_amount DECIMAL(19,2), points_amount BIGINT, voucher_code VARCHAR(255),"
                + "status VARCHAR(30) NOT NULL, decision_code VARCHAR(60), rejection_reason VARCHAR(500), calculated_at TIMESTAMP, posted_at TIMESTAMP, details_json CLOB,"
                + "CONSTRAINT uk_reward_source_benefit_campaign UNIQUE(source_type, source_ref, benefit_type, campaign_id))");
    }
}
