package com.afriland.ticket2cash.rewards;

public enum RewardDecisionCode {
    APPROVED,
    REJECTED_INVALID_AMOUNT,
    REJECTED_MISSING_SOURCE,
    REJECTED_MISSING_CUSTOMER,
    REJECTED_MISSING_BENEFIT_TYPE,
    REJECTED_INVALID_VALUE,
    REJECTED_MISSING_VOUCHER_CODE,
    REJECTED_UNSUPPORTED_BENEFIT,
    REJECTED_DUPLICATE
}
